# Generated by Django 5.2.6 on 2025-09-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Creator', 'Créateur'), ('Suscriber', 'Abonné')], max_length=30, verbose_name='Rôle'),
        ),
    ]
