# Generated by Django 5.2.6 on 2025-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_user_profile_photo_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Creator', 'Créateur'), ('Subscriber', 'Abonné')], default='Subscriber', max_length=30, verbose_name='Rôle'),
        ),
    ]
