# Generated by Django 5.2.6 on 2025-09-22 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_create_creators_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'role': 'Creator'}, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
