# Generated by Django 5.2.6 on 2025-09-22 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'role': 'Creator'}, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
