# Generated by Django 5.2.6 on 2025-09-23

from django.db import migrations

def assign_add_blog_permission_to_creators(apps, schema_editor):
    # Modèles historiques
    User = apps.get_model('authentification', 'User')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Blog = apps.get_model('blog', 'Blog')

    # Récupérer la permission "add_blog"
    content_type = ContentType.objects.get_for_model(Blog)
    add_blog_perm = Permission.objects.get(codename='add_blog', content_type=content_type)

    # Attribuer la permission aux utilisateurs "Creator"
    creators = User.objects.filter(role='Creator')
    for user in creators:
        # Utiliser le champ ManyToMany user_permissions
        if add_blog_perm not in user.user_permissions.all():
            user.user_permissions.add(add_blog_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_tags'),
    ]

    operations = [
        migrations.RunPython(assign_add_blog_permission_to_creators),
    ]